### ISSUE TITLE
win 10无法运行，提示报错如下

### ISSUE THREAD

**Issue by Oli011** [NeptuneIsTheBest/Music-Downloader_TJS#3]
---------------------------
运行时错误
---------------------------
缺少Bass.dll，部分播放功能可能无法使用，请前往 https://www.un4seen.com/ 下载Bass.dll后放入程序根目录
---------------------------
确定   
---------------------------

---------------------------
运行时错误
---------------------------
运行时错误

无法找到成员 "QMS_PlayerControl_loop" 
---------------------------
确定   
---------------------------

**Comment by NeptuneIsTheBest** [comment]
您好，请您在软件运行目录下找到krkr.console.log文件并上传以便更详细的了解问题。

**Comment by NeptuneIsTheBest** [comment]
该问题可能已经在0.2.10.1中修复
