### ISSUE TITLE
能不能搞个歌单下载

### ISSUE THREAD

**Issue by energymf1992** [NeptuneIsTheBest/Music-Downloader_TJS#4]
之前有个软件叫musictool 可以歌单下载
要一首一首点着下
可以开发个歌单下载么? 就是右键网易云程序有个地址 然后会显示歌单歌曲 点着下
我是个特别爱听歌的人
网易云vip每个月就300首 不太够
我可以捐点钱 多没有 可以给200 因为疫情 我收入也不多
我绝不拿去卖 因为我电脑就有15万首歌 我很爱听歌.而且之前那个软件知道的人也不多 但是是在一个软件网站上 下的人还是有点
我就是希望作者你可以做个软件 知道的人不多 我可以多下点.不管能不能做出来,先说声谢谢.

**Comment by NeptuneIsTheBest** [comment]
非常感谢你对这个项目的支持。

其实比较早期的版本中曾经支持过网易源的多种搜索方式，包括但不限于搜索歌单、歌手、歌词、专辑等等，但是后来由于API的反复变动导致这个功能失效，因此我暂时移除了这个功能。
近期大概会整出一个能一个一个下载的歌单下载吧，因为之前的设计的问题导致现在没有办法很好的处理队列下载的问题，估计还要很长的一段时间才能完善歌单的功能。
